{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ting-member-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # ✅ /member/aaa → /aaa로 rewrite
    cert-manager.io/cluster-issuer: letsencrypt-prod  # ✅ cert-manager에게 HTTPS 인증서 요청 위임

spec:
  ingressClassName: nginx  # ✅ nginx ingress controller를 사용
  tls:
    - hosts:
        - {{ .Values.backend.ingress.host }}  # ✅ 예: chat-ting.shop
      secretName: chat-ting-tls  # ✅ 인증서 저장될 시크릿 이름 (자동 생성됨)

  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: /member(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-ting-member
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /chatting(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-ting-server
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
