apiVersion: v1
kind: Service
metadata:
  name: chat-ting-member-db
  labels:
    app: chat-ting-member-db
spec:
  type: ClusterIP
  selector:
    app: chat-ting-member-db
  ports:
    - port: 5432
      targetPort: 5432
