apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-ting-member-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2  # EKS 기본, 필요 시 gp3로 변경 가능
