server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC ????? ?????.
    url: jdbc:postgresql://localhost:5422/reaction?serverTimezone=UTC # ?????? ?? 'shop' ??????? ???? ?? JDBC URL???.
    platform: postgres # ???? ?????? ???? ?????.
    username: rkskekfk # ?????? ??? ?? ??? ?????.
    password: rkskekfk # ?????? ??? ?? ???????.
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false  # Open-Session-In-View ??? ??????, ? ??? ???? ?? ?? ??? ?????.
    properties:
      hibernate:
        show_sql: false  # Hibernate? ???? SQL? ??? ?????.
        default_batch_fetch_size: 100  # ?? ?? ???? 100?? ?????. ? ?? ??? ?? ???? ?????.
        dialect: org.hibernate.dialect.PostgreSQLDialect  # ?????? ??
        format_sql: true  # SQL ??? ?? ?? ????? ?????.
        use_sql_comments: true  # SQL ??? ??? ??????.
  servlet:
    multipart:
      enabled: true  # ????(?? ??? ?) ??? ??????.
      max-file-size: 300MB  # ?? ?? ??? 100MB? ?????.
      max-request-size: 300MB  # ?? ?? ??? 100MB? ?????.
#      file-size-threshold: 2MB
#      location: /tmp
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: new_post
      auto-offset-reset: earliest
#      enable-auto-commit: false  # 자동 오프셋 커밋을 끔

kakao:
  host-name: KAKAO
  client-id: 9f5301883be53d41cb71e73477880f09
  client-secret: vqB5MUBR3aqfL0DDaKkJGO8S5NagiyuB
  redirect-uri: http://123.213.205.236:8080/api/rest/kakao/callback
  logout-redirect-uri: http://123.213.205.236:8080/

jwt:
  secret-key: tempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkey
  access-token-expiration-time: 900000 #60*15*1000
  refresh-token-expiration-time: 259200000 #60*60*24*3*1000

